{
 "about": {
  "channels": [
   "https://conda.anaconda.org/conda-forge/osx-64",
   "https://conda.anaconda.org/conda-forge/noarch",
   "https://repo.continuum.io/pkgs/free/osx-64",
   "https://repo.continuum.io/pkgs/free/noarch",
   "https://repo.continuum.io/pkgs/pro/osx-64",
   "https://repo.continuum.io/pkgs/pro/noarch"
  ],
  "conda_build_version": "2.1.10",
  "conda_env_version": "4.2.13",
  "conda_private": false,
  "conda_version": "4.2.13",
  "dev_url": "https://github.com/zopefoundation/ZEO",
  "doc_url": "https://github.com/zopefoundation/ZEO",
  "env_vars": {
   "CIO_TEST": "<not set>",
   "CONDA_DEFAULT_ENV": "root",
   "CONDA_ENVS_PATH": "<not set>",
   "DYLD_LIBRARY_PATH": "<not set>",
   "PATH": "/Users/travis/miniconda3/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p643/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
   "PYTHONHOME": "<not set>",
   "PYTHONPATH": "<not set>"
  },
  "home": "https://github.com/zopefoundation/ZEO",
  "license": "ZPL 2.1",
  "license_family": "OTHER",
  "offline": false,
  "root_pkgs": [
   "conda-forge::anaconda-client-1.6.3-py36_0",
   "conda-forge::beautifulsoup4-4.5.3-py36_0",
   "cffi-1.9.1-py36_0",
   "conda-forge::chardet-3.0.2-py36_1",
   "conda-forge::clyent-1.2.1-py36_0",
   "conda-forge::conda-4.2.13-py36_0",
   "conda-forge::conda-build-2.1.10-py36_0",
   "conda-forge::conda-env-2.6.0-0",
   "conda-forge::conda-forge-build-setup-4.4.4-0",
   "conda-forge::conda-verify-2.0.0-py36_0",
   "cryptography-1.7.1-py36_0",
   "conda-forge::filelock-2.0.6-py36_0",
   "idna-2.2-py36_0",
   "conda-forge::jinja2-2.9.5-py36_0",
   "conda-forge::markupsafe-1.0-py36_0",
   "openssl-1.0.2k-1",
   "pip-9.0.1-py36_1",
   "conda-forge::pkginfo-1.2.1-py36_0",
   "pyasn1-0.1.9-py36_0",
   "pycosat-0.6.1-py36_1",
   "pycparser-2.17-py36_0",
   "conda-forge::pycrypto-2.6.1-py36_1",
   "pyopenssl-16.2.0-py36_0",
   "python-3.6.0-0",
   "conda-forge::python-dateutil-2.6.0-py36_0",
   "conda-forge::pytz-2017.2-py36_0",
   "conda-forge::pyyaml-3.12-py36_1",
   "readline-6.2-2",
   "requests-2.12.4-py36_0",
   "ruamel_yaml-0.11.14-py36_1",
   "setuptools-27.2.0-py36_0",
   "six-1.10.0-py36_0",
   "sqlite-3.13.0-0",
   "tk-8.5.18-0",
   "wheel-0.29.0-py36_0",
   "xz-5.2.2-1",
   "yaml-0.1.6-0",
   "zlib-1.2.8-3"
  ],
  "summary": "ZEO - Single-server client-server database server for ZODB"
 },
 "conda_build_config": {},
 "files": [
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/runzeo.py",
  "lib/python3.6/site-packages/ZEO/asyncio/__init__.py",
  "lib/python3.6/site-packages/ZEO/scripts/tests.py",
  "lib/python3.6/site-packages/ZEO/tests/testZEOServer.py",
  "lib/python3.6/site-packages/ZEO/tests/protocols.test",
  "lib/python3.6/site-packages/ZEO/asyncio/tests.py",
  "lib/python3.6/site-packages/ZEO/tests/CommitLockTests.py",
  "lib/python3.6/site-packages/ZEO/scripts/zeopack.py",
  "lib/python3.6/site-packages/ZEO/asyncio/compat.py",
  "lib/python3.6/site-packages/ZEO/tests/stress.py",
  "lib/python3.6/site-packages/ZEO/__init__.py",
  "lib/python3.6/site-packages/ZEO/tests/zdoptions.test",
  "lib/python3.6/site-packages/ZEO/zeoctl.xml",
  "lib/python3.6/site-packages/ZEO/Exceptions.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/auth/base.py",
  "lib/python3.6/site-packages/ZEO/tests/__init__.py",
  "lib/python3.6/site-packages/ZEO/scripts/zeopack.test",
  "lib/python3.6/site-packages/ZEO/zconfig.py",
  "lib/python3.6/site-packages/ZEO/scripts/zeoup.py",
  "lib/python3.6/site-packages/ZEO/shortrepr.py",
  "lib/python3.6/site-packages/ZEO/component.xml",
  "lib/python3.6/site-packages/ZEO/cache.py",
  "lib/python3.6/site-packages/ZEO/ordering.rst",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/__init__.py",
  "lib/python3.6/site-packages/ZEO/tests/testConfig.py",
  "lib/python3.6/site-packages/ZEO/nagios.rst",
  "lib/python3.6/site-packages/ZEO/scripts/zeoqueue.py",
  "lib/python3.6/site-packages/ZEO/tests/utils.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/auth/__init__.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/__init__.py",
  "lib/python3.6/site-packages/ZEO/interfaces.py",
  "lib/python3.6/site-packages/ZEO/tests/IterationTests.py",
  "lib/python3.6/site-packages/ZEO/tests/testssl.py",
  "lib/python3.6/site-packages/ZEO/scripts/cache_stats.py",
  "lib/python3.6/site-packages/ZEO/runzeo.py",
  "lib/python3.6/site-packages/ZEO/tests/testConnection.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/auth/hmac.py",
  "lib/python3.6/site-packages/ZEO/scripts/zeoserverlog.py",
  "bin/zeoctl",
  "lib/python3.6/site-packages/ZEO/tests/server_key.pem",
  "lib/python3.6/site-packages/ZEO/tests/test_client_credentials.py",
  "lib/python3.6/site-packages/ZEO/_compat.py",
  "lib/python3.6/site-packages/ZEO/util.py",
  "lib/python3.6/site-packages/ZEO/tests/test_sync.py",
  "lib/python3.6/site-packages/ZEO/tests/testZEO2.py",
  "lib/python3.6/site-packages/ZEO-5.1.0-py3.6.egg-info/PKG-INFO",
  "lib/python3.6/site-packages/ZEO/tests/zeo_blob_cache.test",
  "lib/python3.6/site-packages/ZEO/scripts/zeoreplay.py",
  "lib/python3.6/site-packages/ZEO/tests/servertesting.py",
  "lib/python3.6/site-packages/ZEO/tests/serverpw_key.pem",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/smac.py",
  "lib/python3.6/site-packages/ZEO/scripts/parsezeolog.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/component.xml",
  "lib/python3.6/site-packages/ZEO/scripts/cache_simul.py",
  "lib/python3.6/site-packages/ZEO/asyncio/client.py",
  "lib/python3.6/site-packages/ZEO/tests/threaded.py",
  "lib/python3.6/site-packages/ZEO/StorageServer.py",
  "lib/python3.6/site-packages/ZEO/TransactionBuffer.py",
  "lib/python3.6/site-packages/ZEO/scripts/timeout.py",
  "lib/python3.6/site-packages/ZEO/tests/zeo-fan-out.test",
  "lib/python3.6/site-packages/ZEO/tests/testTransactionBuffer.py",
  "lib/python3.6/site-packages/ZEO/tests/speed.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/server.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/StorageServer.py",
  "lib/python3.6/site-packages/ZEO/asyncio/README.rst",
  "lib/python3.6/site-packages/ZEO/tests/Cache.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/monitor.py",
  "lib/python3.6/site-packages/ZEO/asyncio/base.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/auth/auth_digest.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/marshal.py",
  "lib/python3.6/site-packages/ZEO/ClientStorage.py",
  "bin/zeopack",
  "lib/python3.6/site-packages/ZEO/tests/testConversionSupport.py",
  "lib/python3.6/site-packages/ZEO/server.xml",
  "lib/python3.6/site-packages/ZEO/tests/client_key.pem",
  "lib/python3.6/site-packages/ZEO/monitor.py",
  "bin/runzeo",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/log.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/connection.py",
  "lib/python3.6/site-packages/ZEO/tests/test_client_side_conflict_resolution.py",
  "lib/python3.6/site-packages/ZEO/asyncio/server.py",
  "bin/zeo-nagios",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/schema.xml",
  "lib/python3.6/site-packages/ZEO/tests/ConnectionTests.py",
  "lib/python3.6/site-packages/ZEO/tests/testZEO.py",
  "lib/python3.6/site-packages/ZEO/schema.xml",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/hash.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/error.py",
  "lib/python3.6/site-packages/ZEO/asyncio/mtacceptor.py",
  "lib/python3.6/site-packages/ZEO/tests/new_addr.test",
  "lib/python3.6/site-packages/ZEO/scripts/__init__.py",
  "lib/python3.6/site-packages/ZEO/asyncio/testing.py",
  "lib/python3.6/site-packages/ZEO/tests/client-config.test",
  "lib/python3.6/site-packages/ZEO/nagios.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/_hmac.py",
  "lib/python3.6/site-packages/ZEO/tests/dynamic_server_ports.test",
  "lib/python3.6/site-packages/ZEO/zeoctl.py",
  "lib/python3.6/site-packages/ZEO/tests/client.pem",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/README.rst",
  "lib/python3.6/site-packages/ZEO/tests/serverpw.pem",
  "lib/python3.6/site-packages/ZEO/tests/test_cache.py",
  "lib/python3.6/site-packages/ZEO/asyncio/marshal.py",
  "lib/python3.6/site-packages/ZEO/hash.py",
  "lib/python3.6/site-packages/ZEO/tests/testZEOOptions.py",
  "lib/python3.6/site-packages/ZEO-5.1.0-py3.6.egg-info/not-zip-safe",
  "lib/python3.6/site-packages/ZEO/tests/forker.py",
  "lib/python3.6/site-packages/ZEO/tests/InvalidationTests.py",
  "lib/python3.6/site-packages/ZEO/tests/server.pem",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/client.py",
  "lib/python3.6/site-packages/ZEO/tests/ZEO4/zrpc/trigger.py",
  "lib/python3.6/site-packages/ZEO/tests/ThreadTests.py",
  "lib/python3.6/site-packages/ZEO/tests/TestThread.py"
 ],
 "index": {
  "arch": "x86_64",
  "build": "py36_0",
  "build_number": 0,
  "depends": [
   "persistent >=4.1.0",
   "python 3.6*",
   "setuptools",
   "six",
   "transaction >=2.0.3",
   "zc.lockfile",
   "zconfig",
   "zdaemon",
   "zodb >=5.1.1",
   "zope.interface"
  ],
  "license": "ZPL 2.1",
  "license_family": "OTHER",
  "name": "zeo",
  "platform": "osx",
  "subdir": "osx-64",
  "version": "5.1.0"
 },
 "metadata_version": 1,
 "name": "zeo",
 "raw_recipe": "{% set name = \"ZEO\" %}\n{% set version = \"5.1.0\" %}\n{% set bundle = \"tar.gz\" %}\n{% set hash_type = \"sha256\" %}\n{% set hash = \"142edf8fcabaeec8c438319d71a12a1d4461befa9111a073c362b75e481e7522\" %}\n{% set build = 0 %}\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  fn: {{ name }}-{{ version }}.{{ bundle }}\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}\n  {{ hash_type }}: {{ hash }}\n\nbuild:\n  preserve_egg_dir: True\n  entry_points:\n    - zeopack=ZEO.scripts.zeopack:main\n    - runzeo=ZEO.runzeo:main\n    - zeoctl=ZEO.zeoctl:main\n    - zeo-nagios=ZEO.nagios:main\n\n  number: {{ build }}\n  script: python setup.py install --single-version-externally-managed --record=record.txt\n\nrequirements:\n  build:\n    - python\n    - setuptools\n\n  run:\n    - python\n    - setuptools\n    - trollius  # [py2k]\n    - futures  # [py<32]\n    - zodb >=5.1.1\n    - six\n    - transaction >=2.0.3\n    - persistent >=4.1.0\n    - zc.lockfile\n    - zconfig\n    - zdaemon\n    - zope.interface\n\ntest:\n  imports:\n    - ZEO\n    - ZEO.asyncio\n    - ZEO.scripts\n    - ZEO.tests\n    - ZEO.tests.ZEO4\n    - ZEO.tests.ZEO4.auth\n    - ZEO.tests.ZEO4.zrpc\n\n  commands:\n    # no --help option for zeopack: - zeopack --help\n    - runzeo --help\n    - zeoctl --help\n    - zeo-nagios --help\n\nabout:\n  home: https://github.com/zopefoundation/ZEO\n  license_file: LICENSE.txt\n  license: ZPL 2.1\n  license_family: OTHER\n  summary: 'ZEO - Single-server client-server database server for ZODB'\n  dev_url: https://github.com/zopefoundation/ZEO\n  doc_url: https://github.com/zopefoundation/ZEO\n\nextra:\n  recipe-maintainers:\n    - pmlandwehr\n",
 "rendered_recipe": {
  "about": {
   "dev_url": "https://github.com/zopefoundation/ZEO",
   "doc_url": "https://github.com/zopefoundation/ZEO",
   "home": "https://github.com/zopefoundation/ZEO",
   "license": "ZPL 2.1",
   "license_family": "OTHER",
   "license_file": "LICENSE.txt",
   "summary": "ZEO - Single-server client-server database server for ZODB"
  },
  "build": {
   "entry_points": [
    "zeopack=ZEO.scripts.zeopack:main",
    "runzeo=ZEO.runzeo:main",
    "zeoctl=ZEO.zeoctl:main",
    "zeo-nagios=ZEO.nagios:main"
   ],
   "noarch": "",
   "noarch_python": false,
   "number": "0",
   "preserve_egg_dir": "True",
   "script": "python setup.py install --single-version-externally-managed --record=record.txt",
   "string": "py36_0"
  },
  "extra": {
   "final": true,
   "recipe-maintainers": [
    "pmlandwehr"
   ]
  },
  "package": {
   "name": "zeo",
   "version": "5.1.0"
  },
  "requirements": {
   "build": [
    "ca-certificates 2017.4.17 0",
    "certifi 2017.4.17 py36_0",
    "ncurses 5.9 10",
    "openssl 1.0.2k 0",
    "python 3.6.1 3",
    "readline 6.2 0",
    "setuptools 33.1.1 py36_0",
    "sqlite 3.13.0 1",
    "tk 8.5.19 1",
    "xz 5.2.2 0",
    "zlib 1.2.11 0"
   ],
   "run": [
    "python",
    "setuptools",
    "zodb >=5.1.1",
    "six",
    "transaction >=2.0.3",
    "persistent >=4.1.0",
    "zc.lockfile",
    "zconfig",
    "zdaemon",
    "zope.interface"
   ]
  },
  "source": {
   "fn": "ZEO-5.1.0.tar.gz",
   "sha256": "142edf8fcabaeec8c438319d71a12a1d4461befa9111a073c362b75e481e7522",
   "url": "https://pypi.io/packages/source/Z/ZEO/ZEO-5.1.0.tar.gz"
  },
  "test": {
   "commands": [
    "runzeo --help",
    "zeoctl --help",
    "zeo-nagios --help"
   ],
   "imports": [
    "ZEO",
    "ZEO.asyncio",
    "ZEO.scripts",
    "ZEO.tests",
    "ZEO.tests.ZEO4",
    "ZEO.tests.ZEO4.auth",
    "ZEO.tests.ZEO4.zrpc"
   ]
  }
 },
 "version": "5.1.0"
}